language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0

script:
  - ls -al

before_deploy:
  - composer buildphar

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - build/ripstop.phar
  skip_cleanup: true
  on:
    tags: true
    php: 7.0
